version: '3.8'

services:
  fastapi_app:
    build: ./fastapi_app
    container_name: fastapi_app
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    restart: always
    network_mode: host

  telegram_bot:
    build: ./telegram_bot
    container_name: telegram_bot
    depends_on:
      - fastapi_app
    env_file:
      - .env
    ipc: host
    restart: always
    network_mode: host